use_frameworks!

platform :ios, '10.0'

target 'CaulySDKCocoapods_Example' do
#  pod 'CaulySDKCocoapods', :path => '../'
  pod 'CaulySDKCocoapods'

  target 'CaulySDKCocoapods_Tests' do
    inherit! :search_paths

    
  end
end
